apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rs-delete-ui-crash
  namespace: argocd
spec:
  project: default
  source:
    # TODO: change to a Git repo URL your Argo CD can reach (https or ssh)
    repoURL: https://github.com/choejwoo/argocd-example-apps.git
    # TODO: change to the path inside that repo where these manifests live
    path: repro/rs-delete-ui-crash/base
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: rs-delete-ui-crash
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

