apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rs-delete-ui-crash
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/choejwoo/argocd-example-apps.git
    path: repro/base
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: rs-delete-ui-crash
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

