apiVersion: apps/v1
kind: Deployment
metadata:
  name: presync-api
  namespace: default
  labels:
    app.kubernetes.io/name: presync-api
    app.kubernetes.io/part-of: presync-selfheal
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: presync-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: presync-api
    spec:
      containers:
        - name: api
          image: ghcr.io/argoproj/argocd-example-apps/simple-service:0.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: MESSAGE
              value: "hello from presync api"

